# The documentation for the contents of this file can be found at:
# https://docs.gitlab.com/ce/ci/yaml/README.html

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:1.31.0"

build:cargo:
  script:
  - rustc --version && cargo --version
  - cd does-not-exist
