# Copyright (C) 2023-2024 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

#name: Build
#
#on:
#  push:
#
#jobs:
#  build:
#    name: Build
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        # Please update the test workflow cross-compile matrix when adding a new
#        # target here.
#        target: [
#          x86_64-unknown-linux-musl,
#        ]
#    steps:
#      - uses: actions/checkout@v4
#      - uses: taiki-e/setup-cross-toolchain-action@v1
#        with:
#          target: ${{ matrix.target }}
#      - run: |
#          sudo sed -i 's@^# deb-src @deb-src @' /etc/apt/sources.list
#          sudo apt-get update
#          sudo apt-get source libhidapi-dev
#          sudo apt-get build-dep libhidapi-dev
#          sudo apt-get source --compile libhidapi-dev
#          sudo sudo dpkg -i libhidapi-dev
#          cargo install --bin=nitrocli --path=. --root=. --target ${{ matrix.target }}
#      - uses: actions/upload-artifact@v4
#        with:
#          name: nitrocli-${{ matrix.target }}
#          path: bin/nitrocli

# Copyright (C) 2023-2024 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

on:
  push:

jobs:
  build:
    name: Build statically linked binary
    runs-on: ubuntu-latest
    env:
      CC: "musl-gcc -static"
      CXX: "musl-g++ -static"
      TARGET: "x86_64-unknown-linux-musl"
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo sed -i 's@^# deb-src @deb-src @' /etc/apt/sources.list
          sudo apt-get update
          sudo apt-get install musl-dev musl-tools
          sudo ln -s /bin/g++ /bin/musl-g++
          sudo apt-get source libhidapi-dev
          sudo apt-get build-dep libhidapi-dev
          sudo apt-get source --compile libhidapi-dev
          sudo sudo dpkg -i libhidapi*.deb
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: x86_64-unknown-linux-musl
      - run: |
          cargo install --bin=nitrocli --path=. --root=. --target x86_64-unknown-linux-musl
          strip bin/nitrocli
      - uses: actions/upload-artifact@v4
        with:
          name: nitrocli
          path: bin/nitrocli
