# Copyright (C) 2023-2024 Daniel Mueller <deso@posteo.net>
# SPDX-License-Identifier: GPL-3.0-or-later

name: Build

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Please update the test workflow cross-compile matrix when adding a new
        # target here.
        target: [
          x86_64-unknown-linux-musl,
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - run: |
          sudo apt-get install libhidapi-dev
          cargo install --bin=nitrocli --path=. --root=. --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: nitrocli-${{ matrix.target }}
          path: bin/nitrocli
